spring:
  datasource:
    url: jdbc:mysql://localhost:13306/bookdb
    username: maria
    password: mariaMaria
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect

  sql:
    init:
      encoding: UTF-8

  devtools:
    restart:
      enabled: true