spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/bookdb
    username: maria
    password: mariaMaria
    driverClassName: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  sql:
    init:
      encoding: UTF-8

  devtools:
    restart:
      enabled: true